# Generated by Django 4.1.2 on 2023-01-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="name",
            new_name="cityname",
        ),
    ]
