# Generated by Django 4.1.2 on 2023-01-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rtoapp", "0006_learning"),
    ]

    operations = [
        migrations.AddField(
            model_name="learning",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rtoapp.registration",
            ),
        ),
    ]
