# Generated by Django 4.1.2 on 2023-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtoapp", "0008_rename_user_learning_register_learning_rto"),
    ]

    operations = [
        migrations.AddField(
            model_name="learning",
            name="status",
            field=models.CharField(
                blank=True, default="Not Updated Yet", max_length=100, null=True
            ),
        ),
    ]
