# Generated by Django 4.1.2 on 2023-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtoapp", "0010_driving"),
    ]

    operations = [
        migrations.AddField(
            model_name="driving",
            name="drivingnumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
