# Generated by Django 4.1.2 on 2023-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtoapp", "0012_trackinghistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinghistory",
            name="status",
            field=models.CharField(
                blank=True, default="Not Updated Yet", max_length=100, null=True
            ),
        ),
    ]
