# Generated by Django 4.0.2 on 2023-01-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtoapp', '0018_contact2_creationdate_contact2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving',
            name='rto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtoapp.rto'),
        ),
    ]
